package intel

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// JiraClient connects to Jira for ticket creation
type JiraClient struct {
	BaseURL  string
	Username string
	Token    string
	Project  string
	client   *http.Client
}

// JiraIssue represents a ticket
type JiraIssue struct {
	Fields struct {
		Project struct {
			Key string `json:"key"`
		} `json:"project"`
		Summary     string `json:"summary"`
		Description string `json:"description"`
		IssueType   struct {
			Name string `json:"name"`
		} `json:"issuetype"`
		Priority struct {
			Name string `json:"name"`
		} `json:"priority,omitempty"`
		Labels []string `json:"labels,omitempty"`
	} `json:"fields"`
}

// NewJiraClient creates Jira connector
func NewJiraClient(baseURL, username, token, project string) *JiraClient {
	return &JiraClient{
		BaseURL:  baseURL,
		Username: username,
		Token:    token,
		Project:  project,
		client:   &http.Client{Timeout: 15 * time.Second},
	}
}

// CreateVulnTicket creates a Jira ticket for a vulnerability
func (j *JiraClient) CreateVulnTicket(vulnType, target, severity, evidence string) (string, error) {
	if j.BaseURL == "" {
		return "", fmt.Errorf("Jira not configured")
	}

	priority := "Medium"
	if severity == "critical" {
		priority = "Highest"
	} else if severity == "high" {
		priority = "High"
	} else if severity == "low" {
		priority = "Low"
	}

	issue := JiraIssue{}
	issue.Fields.Project.Key = j.Project
	issue.Fields.Summary = fmt.Sprintf("[Nexus-Void] %s found on %s", vulnType, target)
	issue.Fields.Description = fmt.Sprintf(`*Vulnerability Discovered by Nexus-Void AI*

*Target:* %s
*Type:* %s
*Severity:* %s
*Evidence:*
{code}%s{code}

*Recommended Fix:*
- Refer to OWASP guidelines for %s
- Apply patches immediately
- Retest after remediation

This ticket was auto-generated by Nexus-Void Autonomous Security Platform.
`, target, vulnType, severity, evidence, vulnType)
	issue.Fields.IssueType.Name = "Bug"
	issue.Fields.Priority.Name = priority
	issue.Fields.Labels = []string{"nexus-void", "auto-discovered", vulnType}

	url := fmt.Sprintf("%s/rest/api/2/issue", j.BaseURL)
	jsonBody, _ := json.Marshal(issue)

	req, _ := http.NewRequest("POST", url, bytes.NewBuffer(jsonBody))
	req.Header.Set("Authorization", "Basic "+basicAuth(j.Username, j.Token))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := j.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var result struct {
		Key string `json:"key"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	return result.Key, nil
}

// BulkCreateTickets creates Jira tickets for all findings
func BulkCreateTickets(jiraClient *JiraClient, findings []struct {
	Type     string
	URL      string
	Severity string
	Evidence string
}) []string {
	var tickets []string

	for _, f := range findings {
		key, err := jiraClient.CreateVulnTicket(f.Type, f.URL, f.Severity, f.Evidence)
		if err == nil && key != "" {
			tickets = append(tickets, key)
			fmt.Printf("[JIRA] Created ticket: %s for %s\n", key, f.Type)
		}
	}

	return tickets
}

func basicAuth(username, password string) string {
	auth := username + ":" + password
	// In real implementation, base64 encode this
	return fmt.Sprintf("Basic %s", auth) // Simplified - should be base64
}
